//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod courses;
pub mod notes;
pub mod problem_descriptions;
pub mod problem_tasks;
pub mod problems;
pub mod sea_orm_active_enums;
pub mod submissions;
pub mod users;
