//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::courses::Entity as Courses;
pub use super::notes::Entity as Notes;
pub use super::problem_descriptions::Entity as ProblemDescriptions;
pub use super::problem_tasks::Entity as ProblemTasks;
pub use super::problems::Entity as Problems;
pub use super::submissions::Entity as Submissions;
pub use super::users::Entity as Users;
