//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "problem_tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub test_case_count: i32,
    pub score: i32,
    pub time_limit: i32,
    pub memory_limit: i32,
    pub problem_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::problems::Entity",
        from = "Column::ProblemId",
        to = "super::problems::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Problems,
}

impl Related<super::problems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Problems.def()
    }
}
